/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 16:18:01 GMT 2026
 */

package org.apache.zookeeper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.jute.Record;
import org.apache.zookeeper.ClientCnxn;
import org.apache.zookeeper.ClientCnxnSocket;
import org.apache.zookeeper.Op;
import org.apache.zookeeper.ZooKeeper;
import org.apache.zookeeper.client.HostProvider;
import org.apache.zookeeper.client.ZKClientConfig;
import org.apache.zookeeper.data.Stat;
import org.apache.zookeeper.proto.ReplyHeader;
import org.apache.zookeeper.proto.RequestHeader;
import org.apache.zookeeper.server.DumbWatcher;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true) 
public class ClientCnxn_ESTest extends ClientCnxn_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DumbWatcher dumbWatcher0 = new DumbWatcher(0L);
      byte[] byteArray0 = new byte[2];
      ClientCnxn clientCnxn0 = null;
      try {
        clientCnxn0 = new ClientCnxn((HostProvider) null, 0, 0, (ZKClientConfig) null, dumbWatcher0, (ClientCnxnSocket) null, 0L, byteArray0, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.ClientCnxn", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      RequestHeader requestHeader0 = new RequestHeader();
      ReplyHeader replyHeader0 = new ReplyHeader();
      Stat stat0 = new Stat(0L, 375L, 0L, (-3498L), 0, 0, 39, (-1268L), 39, 0, 39);
      ClientCnxn.Packet clientCnxn_Packet0 = new ClientCnxn.Packet(requestHeader0, replyHeader0, replyHeader0, stat0, (ZooKeeper.WatchRegistration) null);
      clientCnxn_Packet0.serverPath = "";
      String string0 = clientCnxn_Packet0.toString();
      assertEquals("clientPath:null serverPath: finished:false header:: 0,0  replyHeader:: 0,0,0  request:: 0,0,0  response:: 0,375,0,-3498,0,0,39,-1268,39,0,39 ", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DumbWatcher dumbWatcher0 = new DumbWatcher((byte) (-1));
      ClientCnxn clientCnxn0 = null;
      try {
        clientCnxn0 = new ClientCnxn((HostProvider) null, (byte) (-1), (byte) (-1), (ZKClientConfig) null, dumbWatcher0, (ClientCnxnSocket) null, 0L, (byte[]) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.ClientCnxn", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      RequestHeader requestHeader0 = new RequestHeader();
      ReplyHeader replyHeader0 = new ReplyHeader();
      ClientCnxn.Packet clientCnxn_Packet0 = new ClientCnxn.Packet(requestHeader0, replyHeader0, requestHeader0, replyHeader0, (ZooKeeper.WatchRegistration) null);
      clientCnxn_Packet0.createBB();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      RequestHeader requestHeader0 = new RequestHeader();
      ClientCnxn.Packet clientCnxn_Packet0 = new ClientCnxn.Packet(requestHeader0, (ReplyHeader) null, (Record) null, (Record) null, (ZooKeeper.WatchRegistration) null);
      clientCnxn_Packet0.createBB();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ReplyHeader replyHeader0 = new ReplyHeader();
      Op.GetChildren op_GetChildren0 = new Op.GetChildren("Error while calling watcher.");
      Record record0 = op_GetChildren0.toRequestRecord();
      ClientCnxn.Packet clientCnxn_Packet0 = new ClientCnxn.Packet((RequestHeader) null, replyHeader0, (Record) null, record0, (ZooKeeper.WatchRegistration) null);
      clientCnxn_Packet0.createBB();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ClientCnxn.AuthData clientCnxn_AuthData0 = new ClientCnxn.AuthData("0x{} queuedBuffer {}", byteArray0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ClientCnxn.EndOfStreamException clientCnxn_EndOfStreamException0 = new ClientCnxn.EndOfStreamException("fHf0iC1L+u Ew?P R");
      String string0 = clientCnxn_EndOfStreamException0.toString();
      assertEquals("EndOfStreamException: fHf0iC1L+u Ew?P R", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = ClientCnxn.isInEventThread();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DumbWatcher dumbWatcher0 = new DumbWatcher((byte)1);
      ClientCnxn clientCnxn0 = null;
      try {
        clientCnxn0 = new ClientCnxn((HostProvider) null, (byte)1, (ZKClientConfig) null, dumbWatcher0, (ClientCnxnSocket) null, (byte)1, (byte[]) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.ClientCnxn", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DumbWatcher dumbWatcher0 = new DumbWatcher();
      ClientCnxn clientCnxn0 = null;
      try {
        clientCnxn0 = new ClientCnxn((HostProvider) null, (byte)1, (ZKClientConfig) null, dumbWatcher0, (ClientCnxnSocket) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.ClientCnxn", e);
      }
  }
}
