/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Jun 08 16:18:01 GMT 2026
 */

package org.apache.zookeeper;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class ClientCnxn_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.zookeeper.ClientCnxn"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ClientCnxn_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.zookeeper.CreateMode",
      "org.apache.zookeeper.KeeperException$NoWatcherException",
      "org.apache.jute.BinaryOutputArchive",
      "org.apache.zookeeper.client.HostProvider",
      "org.apache.zookeeper.ZooKeeper$States",
      "org.apache.jute.InputArchive",
      "org.apache.zookeeper.WatchDeregistration",
      "org.apache.zookeeper.ZooKeeper$AddWatchRegistration",
      "org.apache.zookeeper.ClientCnxn$WatcherSetEventPair",
      "org.apache.zookeeper.data.Stat",
      "org.apache.zookeeper.ClientCnxn$SessionExpiredException",
      "org.apache.zookeeper.CreateOptions",
      "org.apache.zookeeper.ClientCnxn$SendThread",
      "org.apache.zookeeper.Op$OpKind",
      "org.apache.zookeeper.Op$CreateTTL",
      "org.apache.zookeeper.server.ServerCnxn",
      "org.apache.zookeeper.Op$GetChildren",
      "org.apache.zookeeper.ZooKeeper$DataWatchRegistration",
      "org.apache.zookeeper.proto.ConnectRequest",
      "org.apache.zookeeper.ZooKeeper",
      "org.apache.zookeeper.ClientCnxnSocket",
      "org.apache.zookeeper.Op",
      "org.apache.zookeeper.ClientCnxn$SessionTimeoutException",
      "org.apache.zookeeper.ZooKeeper$ChildWatchRegistration",
      "org.apache.zookeeper.Op$Create",
      "org.apache.zookeeper.server.ZooKeeperThread",
      "org.apache.jute.Record",
      "org.apache.zookeeper.common.ZKConfig",
      "org.apache.zookeeper.proto.RequestHeader",
      "org.apache.zookeeper.Op$GetData",
      "org.apache.zookeeper.Op$Check",
      "org.apache.zookeeper.proto.GetChildrenRequest",
      "org.apache.zookeeper.ZooKeeper$ServerDataWatchRegistration",
      "org.apache.zookeeper.ClientCnxn$LocalCallback",
      "org.apache.zookeeper.server.ServerWatcher",
      "org.apache.zookeeper.proto.ReplyHeader",
      "org.apache.zookeeper.compat.ProtocolManager",
      "org.apache.zookeeper.ClientWatchManager",
      "org.apache.zookeeper.client.ZooKeeperSaslClient",
      "org.apache.zookeeper.ClientCnxn",
      "org.apache.zookeeper.ZooKeeper$ExistsWatchRegistration",
      "org.apache.zookeeper.ClientCnxn$AuthData",
      "org.apache.zookeeper.server.ServerCnxn$DisconnectReason",
      "org.apache.zookeeper.ClientCnxn$Packet",
      "org.apache.zookeeper.ClientCnxn$EndOfStreamException",
      "org.apache.zookeeper.Op$SetData",
      "org.apache.zookeeper.Op$Delete",
      "org.apache.jute.OutputArchive",
      "org.apache.zookeeper.client.ZKClientConfig",
      "org.apache.zookeeper.KeeperException",
      "org.apache.zookeeper.ClientCnxn$ConnectionTimeoutException",
      "org.apache.zookeeper.Watcher",
      "org.apache.zookeeper.ZooKeeper$WatchRegistration",
      "org.apache.zookeeper.WatchedEvent",
      "org.apache.jute.ToStringOutputArchive",
      "org.apache.zookeeper.data.Id",
      "org.apache.zookeeper.Watcher$Event$EventType",
      "org.apache.zookeeper.ClientCnxn$RWServerFoundException",
      "org.apache.zookeeper.ZKWatchManager",
      "org.apache.zookeeper.server.Stats",
      "org.apache.zookeeper.AsyncCallback",
      "org.apache.zookeeper.ClientCnxn$EventThread",
      "org.apache.zookeeper.server.DumbWatcher"
    );
  } 
}
