/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 14:07:06 GMT 2026
 */

package org.apache.zookeeper.server.quorum.flexible;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Properties;
import java.util.Set;
import java.util.TreeSet;
import org.apache.zookeeper.server.ServerConfig;
import org.apache.zookeeper.server.quorum.QuorumPeer;
import org.apache.zookeeper.server.quorum.QuorumPeerConfig;
import org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C3;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true) 
public class QuorumHierarchical_C3_ESTest extends QuorumHierarchical_C3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      QuorumHierarchical_C3 quorumHierarchical_C3_1 = new QuorumHierarchical_C3(properties0);
      quorumHierarchical_C3_1.setVersion(483L);
      boolean boolean0 = quorumHierarchical_C3_0.equals(quorumHierarchical_C3_1);
      assertEquals(483L, quorumHierarchical_C3_1.getVersion());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      quorumHierarchical_C3_0.setVersion(900000L);
      long long0 = quorumHierarchical_C3_0.getVersion();
      assertEquals(900000L, long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      quorumHierarchical_C3_0.setVersion((-927L));
      long long0 = quorumHierarchical_C3_0.getVersion();
      assertEquals((-927L), long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      // Undeclared exception!
      try { 
        quorumHierarchical_C3_0.containsQuorum((Set<Long>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C3", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = null;
      try {
        quorumHierarchical_C3_0 = new QuorumHierarchical_C3((Properties) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C3", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = null;
      try {
        quorumHierarchical_C3_0 = new QuorumHierarchical_C3((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      long long0 = quorumHierarchical_C3_0.getVersion();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      quorumHierarchical_C3_0.getAllMembers();
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TreeSet<Long> treeSet0 = new TreeSet<Long>();
      Long long0 = new Long(2L);
      treeSet0.add(long0);
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      boolean boolean0 = quorumHierarchical_C3_0.containsQuorum(treeSet0);
      assertFalse(boolean0);
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TreeSet<Long> treeSet0 = new TreeSet<Long>();
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      boolean boolean0 = quorumHierarchical_C3_0.containsQuorum(treeSet0);
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      String string0 = quorumHierarchical_C3_0.toString();
      assertEquals("version=0", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumPeer.LearnerType quorumPeer_LearnerType0 = quorumPeerConfig0.getPeerType();
      properties0.put(quorumPeerConfig0, quorumPeer_LearnerType0);
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("G4;~oeym:%CwdGz@iv#");
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3("G4;~oeym:%CwdGz@iv#");
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      boolean boolean0 = quorumHierarchical_C3_0.equals(quorumHierarchical_C3_0);
      assertTrue(boolean0);
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      boolean boolean0 = quorumHierarchical_C3_0.equals(properties0);
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      // Undeclared exception!
      try { 
        quorumHierarchical_C3_0.hashCode();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // hashCode not designed
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = null;
      try {
        quorumHierarchical_C3_0 = new QuorumHierarchical_C3("G4;~oeym:%CwdGz@iv#");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Error processing G4;~oeym:%CwdGz@iv#
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C3", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      quorumHierarchical_C3_0.getObservingMembers();
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      quorumHierarchical_C3_0.setVersion(1207L);
      QuorumHierarchical_C3 quorumHierarchical_C3_1 = new QuorumHierarchical_C3(properties0);
      boolean boolean0 = quorumHierarchical_C3_0.equals(quorumHierarchical_C3_1);
      assertEquals(1207L, quorumHierarchical_C3_0.getVersion());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      quorumHierarchical_C3_0.getVotingMembers();
      assertEquals(0L, quorumHierarchical_C3_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C3 quorumHierarchical_C3_0 = new QuorumHierarchical_C3(properties0);
      // Undeclared exception!
      try { 
        quorumHierarchical_C3_0.getWeight((-1761L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C3", e);
      }
  }
}
