/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 12 15:08:07 GMT 2026
 */

package org.apache.zookeeper.server.quorum.flexible;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedHashSet;
import java.util.Properties;
import java.util.Set;
import org.apache.zookeeper.server.ServerConfig;
import org.apache.zookeeper.server.quorum.QuorumPeerConfig;
import org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C4;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true) 
public class QuorumHierarchical_C4_ESTest extends QuorumHierarchical_C4_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      quorumHierarchical_C4_0.setVersion(1535L);
      QuorumHierarchical_C4 quorumHierarchical_C4_1 = new QuorumHierarchical_C4(properties0);
      boolean boolean0 = quorumHierarchical_C4_0.equals(quorumHierarchical_C4_1);
      assertEquals(1535L, quorumHierarchical_C4_0.getVersion());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      quorumHierarchical_C4_0.setVersion(2L);
      long long0 = quorumHierarchical_C4_0.getVersion();
      assertEquals(2L, long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      quorumHierarchical_C4_0.setVersion((-1115L));
      long long0 = quorumHierarchical_C4_0.getVersion();
      assertEquals((-1115L), long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      // Undeclared exception!
      try { 
        quorumHierarchical_C4_0.containsQuorum((Set<Long>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = null;
      try {
        quorumHierarchical_C4_0 = new QuorumHierarchical_C4((Properties) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C4", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = null;
      try {
        quorumHierarchical_C4_0 = new QuorumHierarchical_C4((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      quorumHierarchical_C4_0.getAllMembers();
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      long long0 = quorumHierarchical_C4_0.getVersion();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      LinkedHashSet<Long> linkedHashSet0 = new LinkedHashSet<Long>();
      Long long0 = new Long((-189L));
      linkedHashSet0.add(long0);
      quorumHierarchical_C4_0.containsQuorum(linkedHashSet0);
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      LinkedHashSet<Long> linkedHashSet0 = new LinkedHashSet<Long>();
      boolean boolean0 = quorumHierarchical_C4_0.containsQuorum(linkedHashSet0);
      assertFalse(boolean0);
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      String string0 = quorumHierarchical_C4_0.toString();
      assertEquals("version=0", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("B*t.,+%g!8lyE");
      byte[] byteArray0 = new byte[6];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4("B*t.,+%g!8lyE");
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      long long0 = quorumHierarchical_C4_0.getWeight(0L);
      assertEquals(0L, long0);
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      QuorumHierarchical_C4 quorumHierarchical_C4_1 = new QuorumHierarchical_C4(properties0);
      quorumHierarchical_C4_1.setVersion(4798L);
      boolean boolean0 = quorumHierarchical_C4_0.equals(quorumHierarchical_C4_1);
      assertEquals(4798L, quorumHierarchical_C4_1.getVersion());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      boolean boolean0 = quorumHierarchical_C4_0.equals((Object) null);
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      boolean boolean0 = quorumHierarchical_C4_0.equals(quorumHierarchical_C4_0);
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      // Undeclared exception!
      try { 
        quorumHierarchical_C4_0.hashCode();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // hashCode not designed
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      quorumHierarchical_C4_0.getObservingMembers();
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      quorumHierarchical_C4_0.getVotingMembers();
      assertEquals(0L, quorumHierarchical_C4_0.getVersion());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = new QuorumHierarchical_C4(properties0);
      QuorumHierarchical_C4 quorumHierarchical_C4_1 = new QuorumHierarchical_C4(properties0);
      boolean boolean0 = quorumHierarchical_C4_0.equals(quorumHierarchical_C4_1);
      assertTrue(boolean0);
      assertEquals(0L, quorumHierarchical_C4_1.getVersion());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      QuorumHierarchical_C4 quorumHierarchical_C4_0 = null;
      try {
        quorumHierarchical_C4_0 = new QuorumHierarchical_C4("B*t.,+%g!8lyE");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Error processing B*t.,+%g!8lyE
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C4", e);
      }
  }
}
