/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 08 16:01:31 GMT 2026
 */

package org.apache.zookeeper.server.quorum.flexible;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Properties;
import java.util.Set;
import java.util.TreeSet;
import org.apache.zookeeper.server.ServerConfig;
import org.apache.zookeeper.server.quorum.QuorumPeerConfig;
import org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true) 
public class QuorumHierarchical_ESTest extends QuorumHierarchical_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      QuorumHierarchical quorumHierarchical1 = new QuorumHierarchical(properties0);
      quorumHierarchical1.setVersion(2093L);
      boolean boolean0 = quorumHierarchical0.equals(quorumHierarchical1);
      assertEquals(2093L, quorumHierarchical1.getVersion());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      QuorumHierarchical quorumHierarchical0 = null;
      try {
        quorumHierarchical0 = new QuorumHierarchical("");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Error processing 
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      assertEquals(0L, quorumHierarchical0.getVersion());
      
      quorumHierarchical0.setVersion(1L);
      long long0 = quorumHierarchical0.getVersion();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      quorumHierarchical0.setVersion((-2089L));
      long long0 = quorumHierarchical0.getVersion();
      assertEquals((-2089L), long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      // Undeclared exception!
      try { 
        quorumHierarchical0.hashCode();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // hashCode not designed
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      // Undeclared exception!
      try { 
        quorumHierarchical0.containsQuorum((Set<Long>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      QuorumHierarchical quorumHierarchical0 = null;
      try {
        quorumHierarchical0 = new QuorumHierarchical((Properties) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      QuorumHierarchical quorumHierarchical0 = null;
      try {
        quorumHierarchical0 = new QuorumHierarchical((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      quorumHierarchical0.getAllMembers();
      assertEquals(0L, quorumHierarchical0.getVersion());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      long long0 = quorumHierarchical0.getVersion();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      TreeSet<Long> treeSet0 = new TreeSet<Long>();
      boolean boolean0 = quorumHierarchical0.containsQuorum(treeSet0);
      assertEquals(0L, quorumHierarchical0.getVersion());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      TreeSet<Long> treeSet0 = new TreeSet<Long>();
      Long long0 = Long.valueOf(3L);
      treeSet0.add(long0);
      boolean boolean0 = quorumHierarchical0.containsQuorum(treeSet0);
      assertEquals(0L, quorumHierarchical0.getVersion());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      String string0 = quorumHierarchical0.toString();
      assertEquals("version=0", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("is in multiple groups");
      byte[] byteArray0 = new byte[4];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical("is in multiple groups");
      assertEquals(0L, quorumHierarchical0.getVersion());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      boolean boolean0 = quorumHierarchical0.equals(quorumHierarchical0);
      assertEquals(0L, quorumHierarchical0.getVersion());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      boolean boolean0 = quorumHierarchical0.equals(quorumPeerConfig0);
      assertFalse(boolean0);
      assertEquals(0L, quorumHierarchical0.getVersion());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      // Undeclared exception!
      try { 
        quorumHierarchical0.getWeight((-121L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      QuorumPeerConfig quorumPeerConfig0 = new QuorumPeerConfig();
      Properties properties0 = quorumPeerConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      quorumHierarchical0.getObservingMembers();
      assertEquals(0L, quorumHierarchical0.getVersion());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ServerConfig serverConfig0 = new ServerConfig();
      Properties properties0 = serverConfig0.getMetricsProviderConfiguration();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      quorumHierarchical0.getVotingMembers();
      assertEquals(0L, quorumHierarchical0.getVersion());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Properties properties0 = new Properties();
      QuorumHierarchical quorumHierarchical0 = new QuorumHierarchical(properties0);
      QuorumHierarchical quorumHierarchical1 = new QuorumHierarchical(properties0);
      quorumHierarchical1.setVersion(2093L);
      boolean boolean0 = quorumHierarchical1.equals(quorumHierarchical0);
      assertEquals(2093L, quorumHierarchical1.getVersion());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      QuorumHierarchical quorumHierarchical0 = null;
      try {
        quorumHierarchical0 = new QuorumHierarchical("is in multiple groups");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Error processing is in multiple groups
         //
         verifyException("org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical", e);
      }
  }
}
