/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jun 12 15:08:07 GMT 2026
 */

package org.apache.zookeeper.server.quorum.flexible;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class QuorumHierarchical_C4_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C4"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(QuorumHierarchical_C4_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.zookeeper.server.quorum.SyncedLearnerTracker",
      "org.apache.zookeeper.server.quorum.QuorumPeer",
      "org.apache.yetus.audience.InterfaceAudience$Public",
      "org.apache.zookeeper.server.quorum.QuorumPeerConfig",
      "org.apache.zookeeper.metrics.MetricsProvider",
      "org.apache.zookeeper.common.ConfigException",
      "org.apache.zookeeper.server.ZooKeeperThread",
      "org.apache.zookeeper.server.quorum.flexible.QuorumVerifier",
      "org.apache.zookeeper.common.AtomicFileWritingIdiom$WriterStatement",
      "org.apache.zookeeper.common.AtomicFileWritingIdiom$OutputStreamStatement",
      "org.apache.zookeeper.server.quorum.QuorumStats$Provider",
      "org.apache.zookeeper.server.ServerConfig",
      "org.apache.zookeeper.server.quorum.LearnerMaster",
      "org.apache.zookeeper.server.quorum.flexible.QuorumHierarchical_C4",
      "org.apache.zookeeper.server.quorum.Leader",
      "org.apache.zookeeper.metrics.impl.DefaultMetricsProvider",
      "org.apache.zookeeper.server.quorum.MultipleAddresses",
      "org.apache.zookeeper.server.quorum.QuorumPeer$ServerState",
      "org.apache.zookeeper.server.quorum.QuorumPeer$LearnerType",
      "org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer",
      "org.apache.zookeeper.server.quorum.QuorumPeer$ZabState",
      "org.apache.zookeeper.server.quorum.QuorumPeer$SyncMode"
    );
  } 
}
