name: ISW2 CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build and Install 
      run: mvn -B clean install -DskipTests -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drat.skip=true

    - name: Run Unit Tests 
      run: mvn -B test -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drat.skip=true -DfailIfNoTests=false

    - name: Run Integration Tests 
      run: mvn -B verify -DskipUnitTests -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drat.skip=true -DfailIfNoTests=false
